DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
id BIGINT NOT NULL AUTO_INCREMENT,
dni BIGINT NOT NULL,
email VARCHAR(30) NOT NULL,
password VARCHAR(70) NOT NULL,
mobile_phone BIGINT NOT NULL,
full_name VARCHAR(20) NOT NULL,
status VARCHAR(15) NOT NULL,
rol VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS NOTIFICATION;
CREATE TABLE NOTIFICATION (
id BIGINT NOT NULL AUTO_INCREMENT,
topic VARCHAR(20) NOT NULL,
title VARCHAR(50) NOT NULL,
area VARCHAR(500) NOT NULL,
message VARCHAR(500) NOT NULL,
date_created DATETIME NOT NULL,
user_created_id BIGINT NOT NULL,
status VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS TOPIC;
CREATE TABLE TOPIC (
id BIGINT NOT NULL AUTO_INCREMENT ,
name VARCHAR(25) NOT NULL,
status VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY (
id BIGINT NOT NULL AUTO_INCREMENT,
lat DECIMAL(10,6) NOT NULL,
lon DECIMAL(10,6) NOT NULL,
city VARCHAR(50) NOT NULL,
state VARCHAR(50) NOT NULL,
status VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
);